package model;

public enum ClientRequest {
   CREATE_ACCOUNT, CHANGE_PASSWORD, LOGIN, LOGOUT,
   CREATE_DOC, OPEN_DOC, CLOSE_DOC, 
   CHAT_MSG, DOC_TEXT, REVERT_DOC,   
   ADD_PERMISSION, REMOVE_PERMISSON;
}
