package model;

public enum ServerResponse {
   LOGIN_SUCCESS, ACCOUNT_CREATED, INCORRECT_USERNAME, INCORRECT_PASSWORD,
   MAX_ATTEMPTS, LOGGED_IN, ACCOUNT_EXISTS, LOGOUT_SUCCESS, PASSWORD_CHANGED,
   DOCUMENT_CREATED, NO_DOCUMENT, DOCUMENT_DELETED, PERMISSION_ADDED, PERMISSION_DENIED
}
