package model;

public enum ServerResponse {
   ACCOUNT_CREATED, INCORRECT_USERNAME, INCORRECT_PASSWORD, LOGIN_SUCCESS, 
   LOGGED_IN, ACCOUNT_EXISTS, PASSWORD_CHANGED, LOGOUT_SUCCESS,
   DOCUMENT_EXISTS, DOCUMENT_CREATED, NO_DOCUMENT, DOCUMENT_DELETED,
   PERMISSION_ADDED, PERMISSION_DENIED
}
